// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using back_congreso_utl.Data;

#nullable disable

namespace back_congreso_utl.Migrations
{
    [DbContext(typeof(CongresoDbContext))]
    [Migration("20251109052125_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("back_congreso_utl.Models.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceptaTerminos")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ocupacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Twitter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("participantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AceptaTerminos = true,
                            Apellidos = "Rubio",
                            Avatar = "👨‍💻",
                            Email = "jrubio@mail.com",
                            Nombre = "Julián",
                            Ocupacion = "Desarrollador de Software",
                            Twitter = "JRubio"
                        },
                        new
                        {
                            Id = 2,
                            AceptaTerminos = true,
                            Apellidos = "Medina",
                            Avatar = "👨‍💼",
                            Email = "rmedina@mail.com",
                            Nombre = "Raúl",
                            Ocupacion = "Ingeniero Front End",
                            Twitter = "RaulMedina"
                        },
                        new
                        {
                            Id = 3,
                            AceptaTerminos = true,
                            Apellidos = "Andrade",
                            Avatar = "🧑‍💻",
                            Email = "candrade@mail.com",
                            Nombre = "Carlos",
                            Ocupacion = "Desarrollador Web Full Stack",
                            Twitter = "CAndrade"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
